### ISSUE TITLE
Does not recover after fail to build with jsx-loader

### ISSUE THREAD

**Issue by mlunoe** [myfreeweb/broccoli-webpack#1]
It seems like when broccoli-webpack fails to compile with the jsx-loader it fails the build (which is fine), but it does not recover after that error. After that error it stays in this state, and does not respond to changes in the file. I have to fix the error, and re-start the build before it will recover, and keep watching for changes.

Here is a stack trace:

```
./tmp/tmp_dest_dir-dpe71F9H.tmp/src/js/stores/MesosStateStore.js
Module build failed: Error: Parse Error: Line 191: Unexpected token ;
  at throwError (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
  at throwUnexpected (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)
  at expect (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2715:13)
  at parseParams (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5616:9)
  at parseFunctionDeclaration (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5682:15)
  at parseSourceElement (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6137:24)
  at parseProgramElement (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6185:16)
  at parseProgramElements (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6217:29)
  at parseProgram (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6230:16)
  at Object.parse (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7566:23)
  at transform (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:224:36)
  at innerTransform (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/main.js:49:10)
  at Object.module.exports.transformWithDetails (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/main.js:23:18)
  at Object.module.exports (/Users/ml/Mesosphere/dcos-ui/node_modules/jsx-loader/index.js:15:30)
 @ ./tmp/tmp_dest_dir-dpe71F9H.tmp/src/js/pages/NodesPage.js 17:22-58 0 [ './tmp/tmp_dest_dir-dpe71F9H.tmp/src/js/stores/MesosStateStore.js\nModule build failed: Error: Parse Error: Line 191: Unexpected token ;\n  at throwError (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)\n  at throwUnexpected (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)\n  at expect (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2715:13)\n  at parseParams (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5616:9)\n  at parseFunctionDeclaration (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5682:15)\n  at parseSourceElement (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6137:24)\n  at parseProgramElement (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6185:16)\n  at parseProgramElements (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6217:29)\n  at parseProgram (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6230:16)\n  at Object.parse (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7566:23)\n  at transform (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:224:36)\n  at innerTransform (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/main.js:49:10)\n  at Object.module.exports.transformWithDetails (/Users/ml/Mesosphere/dcos-ui/node_modules/react-tools/main.js:23:18)\n  at Object.module.exports (/Users/ml/Mesosphere/dcos-ui/node_modules/jsx-loader/index.js:15:30)\n @ ./tmp/tmp_dest_dir-dpe71F9H.tmp/src/js/pages/NodesPage.js 17:22-58' ]
Built with error:
[TypeError: Cannot read property 'message' of null]
```

**Comment by mlunoe** [comment]
I'm not sure this is the broccoli-webpack package or broccoli itself that has the error.

We are using these versions:

```
"broccoli": "0.13.6",
"broccoli-webpack": "0.1.1",
"jsx-loader": "0.12.2",
"transform-loader": "0.2.2"
```

**Comment by valpackett** [comment]
Yeah, I haven't tested for any failures :D Will try to figure something out soon.
